name: MyFirstWorkflow
on: 
  push:
  workflow_dispatch:
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: HelloWorld 
        run: |
          mkdir hello
          echo 'ls -ltr' >> hello/lists.txt
          echo 'HelloWorld' >> hello/helloworlds.txt
      - name: Checking the os Release of machine and running a sleep command for 20 secs
        run: |
          cat /etc/os-release >> os-releases.txt
      - name: Upload Artifact file
        uses: actions/upload-artifact@v7
        with:
          path: ./os-releases.txt
      - name: Upload Artifact from folder with exclusion
        uses: actions/upload-artifact@v7
        with:
          path: |
            hello/
            !**/lists.txt
  job2:
    name: job2 
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checking the hostname
        run: hostname
      - name: Checkout implemented
        uses: actions/checkout@v7
      
